language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install -M tox

script: tox

# before_install:
#   - sudo apt-get update
#   - sudo apt-get install build-essential python-dev libevent-dev python-pip liblzma-dev
